baseurl = "https://c74ce35e.ngrok.io/" # Controls base URL
languageCode = "en-US" # Controls site language
title = "Cataclysm: Bright Nights" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating

theme = "after-dark" # Set default theme

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "" # Suggested, controls default description meta
  author = "" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  images = [
    "https://source.unsplash.com/category/technology/2000x1322"
  ] # Suggested, controls default Open Graph images
  theme_variant = "hack solarized-dark" # Optional, for use to overriding default theme

  [[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
  [[menu.main]]
  name = "Current Release"
  weight = 3
  identifier = "page"
  url = "/current-release/"